---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: rpm

- name: Download Proton Pass Installer
  when: "not 'proton-pass' in ansible_facts.packages"
  ansible.builtin.get_url:
    checksum: "{{ checksum_proton_pass_v1223 }}"
    dest: "{{ local_path_proton_pass }}"
    url: "{{ url_proton_pass }}"
    mode: "0755"
  register: installer_downloaded

- name: Install Proton Pass
  when: installer_downloaded.changed
  ansible.builtin.command:
    cmd: "sudo rpm -i --force {{ local_path_proton_pass }}"
    creates: /usr/bin/proton-pass
