---
- name: Edit how DNF works
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    prepend_newline: true
    append_newline: true
    block: |
      max_parallel_downloads=10
      defaultyes=True
      fastestmirror=True
