# check status
# hx --health languages

[[language]]
name = "markdown"
formatter = { command = "markdown-oxide", args = ["--stdin"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["--stdin"] }

[[language]]
name = "yaml"
formatter = { command = "yq", args = ["eval", "-P", "-i"] }
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--stdin"] }
indent = { tab-width = 2, unit = "  " }
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
language-servers = ["pylsp"]
formatter = { command = "sh", args = ["-c", "isort --stdout | autopep8 --stdin --stdout"] }
indent = { tab-width = 2, unit = "  " }

