---
- name: Remove all DNF cache
  ansible.builtin.command: dnf5 clean all
  register: dnf_clean_output
  changed_when: dnf_clean_output.stdout != "0 files removed"

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf5:
    autoremove: true
