---
- name: Add repo RPM Fusion free
  ansible.builtin.dnf:
    state: present
    disable_gpg_check: true
    name: "{{ url_repo_rpm_fusion_free }}"

- name: Add repo RPM Fusion nonfree
  ansible.builtin.dnf:
    state: present
    disable_gpg_check: true
    name: "{{ url_repo_rpm_fusion_non_free }}"

- name: Add repo Flathub
  community.general.flatpak_remote:
    state: present
    name: flathub
    flatpakrepo_url: "{{ url_repo_flathub }}"
