---
- name: Check if font FiraCode exists
  ansible.builtin.stat:
    path: /usr/local/share/fonts/FiraCodeNerdFont/FiraCodeNerdFontMono-Regular.ttf
  register: font_firacode

- name: Create folder for Font FiraCodeNerdFont
  when: not font_firacode.stat.exists
  ansible.builtin.file:
    mode: "777"
    state: directory
    path: /usr/local/share/fonts/FiraCodeNerdFont
  register: dir_created

- name: Copy files from dotfiles to font directory
  when: dir_created.changed
  ansible.builtin.copy:
    mode: "777"
    dest: /usr/local/share/fonts/FiraCodeNerdFont
    src: /home/andreb/.dotfiles/.misc/fonts/firacodenerdfont/
