---
- name: Check if repo for ProtonVPN exists
  ansible.builtin.dnf:
    name: protonvpn-stable-release
    state: present
  register: repo_exists
  ignore_errors: true

- name: Download repo installer
  when: repo_exists is failed
  ansible.builtin.get_url:
    url: "{{ url_proton_vpn }}"
    dest: "{{ local_path_proton_vpn }}"
    mode: "0755"
    force: true
  register: installer_downloaded

- name: Add repo ProtonVPN
  when: installer_downloaded.changed
  ansible.builtin.dnf:
    name: "{{ local_path_proton_vpn }}"
    state: present
  register: repo_added

- name: Clean up Remove installer
  when: installer_downloaded.changed
  ansible.builtin.file:
    path: "{{ local_path_proton_vpn }}"
    state: absent

- name: Check if desktop app ProtonVPN exists, if not, install it
  when: repo_exists
  ansible.builtin.dnf:
    name: proton-vpn-gnome-desktop
    state: present
  register: protonvpn_exists
