---
- name: DNF - INSTALL - stow
  ansible.builtin.dnf:
    state: present
    name: stow
  register: stow_exists

- name: Stow dotfiles
  when: stow_exists is succeeded
  ansible.builtin.command:
    cmd: stow --restow --dir=/home/andreb/.dots/ --target=/home/andreb/ "{{ apps_stow }}"
  register: stow_output
  changed_when: stow_output.rc != 0
