---
home: "/home/andreb"
local_path_dirs:
  - "{{ home }}/Documents/development"
  - "{{ home }}/.installers"
  - "/usr/local/share/fonts/FiraCodeNerdFont"

rust_rustup_home: "/opt/rust/.rustup"
rust_cargo_home: "/opt/rust/.cargo"
rust_local_path_installer: "/opt/rust/sh.rustup.rs"
rust_local_path_cargo: "{{ cargo_home }}/bin/rustup"
rust_url_installer: "https://sh.rustup.rs"

local_path_rust_installer: "{{ home }}/.installers/sh.rustup.rs"
local_path_cargo: "{{ home }}/.cargo/bin/rustup"

url_repo_rpm_fusion_free: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
url_repo_rpm_fusion_non_free: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
url_repo_flathub: "https://flathub.org/repo/flathub.flatpakrepo"
url_rust_installer: "https://sh.rustup.rs"

apps_stow: "apps"

apps_dnf:
  - alacritty # https://github.com/alacritty/alacritty
  - cmus # https://github.com/cmus/cmus
  - helix # https://github.com/helix-editor/helix
  - newsboat # https://github.com/newsboat/newsboat
  - solaar # logitech options replacement # https://github.com/pwr-Solaar/Solaar
  - tmux # https://github.com/tmux/tmux
  - bat # https://github.com/sharkdp/bat
  - eza # https://github.com/eza-community/eza
  - ripgrep # https://github.com/BurntSushi/ripgrep
  - tealdeer # tlrc not available using dnf as of writing # https://github.com/tealdeer-rs/tealdeer
  - discord # https://github.com/discord
  - qimgv # https://github.com/easymodo/qimgv
  - firefox
  - fd-find # https://github.com/sharkdp/fd
  - fzf # https://github.com/junegunn/fzf
  - htop # https://github.com/htop-dev/htop
  - akmod-nvidia # nvidia graphics drivers, requires rpmfusion non-free

apps_flatpak:
  - com.bitwarden.desktop
  - com.notepadqq.Notepadqq
  - com.spotify.Client
  - com.valvesoftware.Steam
  - org.kde.Krita
  - org.qbittorrent.qBittorrent
  - org.signal.Signal
  - org.videolan.VLC

apps_cargo:
  - thokr # https://github.com/jrnxf/thokr
  - taplo-cli # LSP-toml https://github.com/tamasfe/taplo
#  - markdown-oxide # LSP-markdown https://github.com/Feel-ix-343/markdown-oxide

dnf_bloatware:
  - akregator
  - dragon
  - elisa-player
  - filelight
  - gwenview
  - ibus-typing-booster
  - kaddressbook
  - kamoso
  - kate
  - kcharselect
  - kde-connect
  - kmahjongg
  - kmail
  - kmines
  - kmousetool
  - kmouth
  - korganizer
  - kolourpaint
  - kontact
  - kpat
  - krdc
  - krfb
  - ktnef
  - kwrite
  - libreoffice-core
  - mediawriter
  - neochat
  - okular
  - skanpage
