---
home: "/home/andreb"
local_path_dirs:
  - "{{ home }}/Documents/development"
  - "{{ home }}/.installers"

local_path_proton_vpn: "{{ home }}/.installers/proton_vpn.rpm"
local_path_proton_pass: "{{ home }}/.installers/proton_pass.rpm"
local_path_rust_installer: "{{ home }}/.installers/sh.rustup.rs"
local_path_cargo: "{{ home }}/.cargo/bin/rustup"

url_repo_rpm_fusion_free: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
url_repo_rpm_fusion_non_free: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
url_repo_flathub: "https://flathub.org/repo/flathub.flatpakrepo"
url_proton_vpn: "https://repo.protonvpn.com/fedora-{{ ansible_distribution_major_version }}-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.1-2.noarch.rpm"
url_proton_pass: "https://proton.me/download/PassDesktop/linux/x64/ProtonPass.rpm"
url_rust_installer: "https://sh.rustup.rs"

checksum_proton_pass_v1223: sha512:e8d2aaf9c215e0db52432117a123ef48c6f659c78ae06545b5d331fb55de243718b1a334e39cd2dadc7de5864421ed519c5d042529a9386098704b693aa0f540

apps_stow: "apps"

apps_dnf:
  - alacritty # https://github.com/alacritty/alacritty
  - cmus # https://github.com/cmus/cmus
  - code # https://github.com/microsoft/vscode
  - fish # https://github.com/fish-shell/fish-shell
  - helix # https://github.com/helix-editor/helix
  - newsboat # https://github.com/newsboat/newsboat
  - solaar # logitech options replacement # https://github.com/pwr-Solaar/Solaar
  - tmux # https://github.com/tmux/tmux
  - bat # https://github.com/sharkdp/bat
  - eza # https://github.com/eza-community/eza
  - ripgrep # https://github.com/BurntSushi/ripgrep
  - tealdeer # tlrc not available using dnf as of writing # https://github.com/tealdeer-rs/tealdeer
  - discord # https://github.com/discord
  - qimgv # https://github.com/easymodo/qimgv
  - firefox
  - fd-find # https://github.com/sharkdp/fd
  - fzf # https://github.com/junegunn/fzf
  - htop # https://github.com/htop-dev/htop
  - akmod-nvidia # nvidia graphics drivers, requires rpmfusion non-free

apps_flatpak:
  - com.bitwarden.desktop
  - com.spotify.Client
  - com.valvesoftware.Steam
  - org.qbittorrent.qBittorrent
  - org.signal.Signal
  - org.videolan.VLC

apps_cargo:
  - thokr # https://github.com/jrnxf/thokr
  - taplo-cli # https://github.com/tamasfe/taplo
  - markdown-oxide # https://github.com/Feel-ix-343/markdown-oxide
  - slint-lsp # https://github.com/slint-ui/slint/tree/HEAD/tools/lsp

dnf_bloatware:
  - akregator
  - dragon
  - elisa-player
  - filelight
  - gwenview
  - ibus-typing-booster
  - kaddressbook
  - kamoso
  - kate
  - kcharselect
  - kde-connect
  - kmahjongg
  - kmail
  - kmines
  - kmousetool
  - kmouth
  - korganizer
  - kolourpaint
  - kontact
  - kpat
  - krdc
  - krfb
  - ktnef
  - kwrite
  - libreoffice-core
  - neochat
  - okular
  - skanpage

vscode_extensions:
  - catppuccin.catppuccin-vsc
  - gruntfuggly.todo-tree
  - mechatroner.rainbow-csv
  - mohsen1.prettify-json
  - ms-python.python
  - pkief.material-icon-theme
  - redhat.ansible
  - redhat.vscode-yaml
  - rust-lang.rust-analyzer
  - tamasfe.even-better-toml
