# [shell]
# program = "/usr/bin/fish"

[general]
live_config_reload = true
import = ["catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"       # Full / None
# opacity = 0.8
# blur = true
padding = { x = 3, y = 0 } # x=left+right | y=top+bottom
dynamic_padding = true     # sets same padding in all 4 directions

[window.dimensions]
columns = 144
lines = 60

[font]
size = 12.00
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true

[scrolling]
history = 50_000
multiplier = 1

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
]

[colors]
draw_bold_text_with_bright_colors = true

