# [shell]
# program = "/usr/bin/fish"

[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"       # Full / None
# opacity = 0.8
# blur = true
padding = { x = 3, y = 0 } # x=left+right | y=top+bottom
dynamic_padding = true     # sets same padding in all 4 directions

[window.dimensions]
columns = 144
lines = 60

[font]
size = 12.00
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true

[scrolling]
history = 50_000
multiplier = 1

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
]

[colors]
draw_bold_text_with_bright_colors = true

# https://github.com/catppuccin/catppuccin
## catppuccin frappe
[colors.primary]
background = "#303446"
foreground = "#c6d0f5"
dim_foreground = "#838ba7"
bright_foreground = "#c6d0f5"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#303446"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#303446"
background = "#a6d189"

[colors.footer_bar]
foreground = "#303446"
background = "#a5adce"

[colors.hints.start]
foreground = "#303446"
background = "#e5c890"

[colors.hints.end]
foreground = "#303446"
background = "#a5adce"

[colors.selection]
text = "#303446"
background = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"

## catppuccin macchiato
# [colors.primary]
# background = "#24273a"
# foreground = "#cad3f5"
# dim_foreground = "#8087a2"
# bright_foreground = "#cad3f5"

# [colors.cursor]
# text = "#24273a"
# cursor = "#f4dbd6"

# [colors.vi_mode_cursor]
# text = "#24273a"
# cursor = "#b7bdf8"

# [colors.search.matches]
# foreground = "#24273a"
# background = "#a5adcb"

# [colors.search.focused_match]
# foreground = "#24273a"
# background = "#a6da95"

# [colors.footer_bar]
# foreground = "#24273a"
# background = "#a5adcb"

# [colors.hints.start]
# foreground = "#24273a"
# background = "#eed49f"

# [colors.hints.end]
# foreground = "#24273a"
# background = "#a5adcb"

# [colors.selection]
# text = "#24273a"
# background = "#f4dbd6"

# [colors.normal]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"

# [colors.bright]
# black = "#5b6078"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#a5adcb"

# [colors.dim]
# black = "#494d64"
# red = "#ed8796"
# green = "#a6da95"
# yellow = "#eed49f"
# blue = "#8aadf4"
# magenta = "#f5bde6"
# cyan = "#8bd5ca"
# white = "#b8c0e0"

# [[colors.indexed_colors]]
# index = 16
# color = "#f5a97f"

# [[colors.indexed_colors]]
# index = 17
# color = "#f4dbd6"
